Repository moia-oss/tinytime.rs, pull requests merged in 2023-10, with the labels that each got.

#40 Fix version definition
  Cargo.toml
Labels: norelease

#41 Fix norelease labels
  .github/workflows/publish.yaml
  Cargo.toml
Labels: norelease, hacktoberfest-accepted

#39 Add TimeWindow::intersect function
  src/lib.rs
Labels: release:minor, hacktoberfest-accepted

#42 Proper fix for norelease checks
  .github/workflows/publish.yaml
Labels: release:patch

#43 Implement TimeWindow::contains
  src/lib.rs
Labels: hacktoberfest-accepted

#44 Add shrink_towards_X_to functions
  src/lib.rs
Labels: release:minor, hacktoberfest-accepted

#45 Remove rust cache from semver check
  .github/workflows/pr.yaml
Labels: norelease

#46 Ensure invariant that TimeWindow::start < end
  Cargo.toml
  src/lib.rs
Labels: release:minor, hacktoberfest-accepted

#47 Time Debug impl
  Cargo.toml
  src/lib.rs
Labels: hacktoberfest-accepted
